### ISSUE TITLE
Prevent FAIL results to appear at the top of the table in result panel

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#110]
When a software crashed, it is flagged as "FAIL" in the result table. These failed line are always at the top of the list when we sort the table.

**Comment by bourgesl** [comment]
Fixed in both jMCS & SearchCal GUI:
https://github.com/JMMC-OpenDev/jmcs/commit/5c0af5077d0950c7d1f4aaad2a1ff38d1b2f891c
