### ISSUE TITLE
Modify image

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#16]
A modify image button that shows a popup to modify an image.
Parameters:
-  image to be modified
- size Field of View
- sampling (pixel size)
- image name?
- overwrite?

**Comment by buthanoid** [comment]
I renamed and reorganized some code. I reworked addFitsImageHDU so it uses the initial version and there is no more duplicate code

**Comment by buthanoid** [comment]
Some bug fixes in #39

**Comment by FerreolS** [comment]
The norm is not completely clear for me.
[`CRPIX`keyword in the reference document](https://archive.stsci.edu/fits/fits_standard/node40.html#SECTION00942560000000000000)

I understand that the image is centered on the center of the pixel CRPIX-th pixel (beginning from 1).

**Comment by FerreolS** [comment]
As said in the document this CRPIX pixel can be outside of the image. So what is the goal of the cross-hair in that case. 
In fact do we really need it? 
Should we center the viewport on the field of view only?
