### ISSUE TITLE
Save image Vs save oifits

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#17]
The behavior of the two button is difficult to understand. 
It seems that
- `save image` saves only the reconstructed image in a fits files
- `save oifits` saves everything as defined in the OI-image definition

Should we keep only a single button `save results ` saving the reconstruction in the OI-image standard. It will be almost transparent for the user as the reconstructed image is in the primary hdu

**Comment by buthanoid** [comment]
When we click on "save oifits" a dialog opens to ask where to write the file.
Could we add an option here to choose which to save, all by default, and "only images" as an option ?

**Comment by bourgesl** [comment]
I think only 1 button is needed like ferreol but it must be active as below:
- INPUT file displayed => save input as OIFITS
- RESULT displayed => save result as OIFITS
- grid / compare => save the corresponding results as OIFITS

I think we should keep a save image action (and send image SAMP action) in the file menu... to export the first image only for simple software like ds9...

**Comment by FerreolS** [comment]
For the grid/compare panel, I don't know what is the best behavior as every results does not have the same parameters. Should we save a collection of OIFITS? Again it is related to the idea of session...

**Comment by buthanoid** [comment]
#31
