### ISSUE TITLE
Beam

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#24]
From the oifits files it is possible to estimate the beam that is: minor, major axes and PA of an ellipse describing the resolution of the interferometer.

**Comment by bourgesl** [comment]
To compute the beam, should we use U-V frequencies from VIS2 tables only or also consider VIS and T3 tables ? Some OIFITS files may not have VIS2 tables, then no beam estimation.
As there is redundancy between tables, how to normalize properly ?

**Comment by FerreolS** [comment]
Good question
All the UV frequencies has to be taken only once. This IMO drives out all T3 tables has I believe that if 3 telescopes are cophased then there must be corresponding VIS2 or VIS for the 3 baselines. (even if, in gravity, the recorded uv of the T3 differs do to integration difference).
For VIS and VIS2, it depends of the instrumental mode. If there is phase reference, we should take the UV of the VIS mainly (no need of V2 in that case), if the VIS contains only differencial quantities, the UV coordinates are probably counted twice in VIS and VIS2 table. As you can have files with mix of these modes, depending of how the tables were built, we probably  need to retrieve all the non-redondant UV coordinate for both table.

**Comment by FerreolS** [comment]
> I propose to compute the beam by estimating the covariance matrix of the (u,v) coordinate of the baseline. Its eigen values will be the axis and the eigenvector will gives the angle of the ellipse in Fourier domain. Then convert to image domain.

To keep track of the information the Julia code, the documentation and a demo for that  is  [here](https://github.com/JMMC-OpenDev/oibeam)

**Comment by bourgesl** [comment]
Here is OImaging beta release that computes the beam on VIS2 only and displays the ellipse at the image center (overlay):
https://www.jmmc.fr/apps/beta/OImaging/

**Comment by bourgesl** [comment]
What algorithm can be used to discard redundant UV coordinate ?
it seems tricky to take precision into account (gridding ?)

**Comment by FerreolS** [comment]
> What algorithm can be used to discard redundant UV coordinate ? it seems tricky to take precision into account (gridding ?)

I don't know. Probably the redondant UV coordinates in VIS and VIS2 have exactly the same value. This has to be checked in practice

**Comment by FerreolS** [comment]
> Here is OImaging beta release that computes the beam on VIS2 only and displays the ellipse at the image center (overlay): https://www.jmmc.fr/apps/beta/OImaging

✔️  I have checked that the plotted ellipse in the exactly the same than in my notebook for RCar

**Comment by bourgesl** [comment]
I updated OImaging beta:
https://www.jmmc.fr/apps/beta/OImaging/

Changes:
- Added the toogle button 'Beam' on image panels to show or hide the beam info (displayed in its tooltip)
- Modified the beam estimation to use distinct spatial frequencies from both OI_VIS and OI_VIS2 tables (with small rounding of spatial frequencies)

I left the beam at the image center as the plot is zoomable

**Comment by jean-philippeberger** [comment]
👍
Ca serait pas mal d’avoir des retours de validation (je vais tester ça dès que je me libère). Je sais que Ferréol a déjà testé la fonctionalité.

JPB
___________________________________________________________________________
Jean-Philippe Berger
Institut de Planétologie et d’Astrophysique de Grenoble            http://ipag.osug.fr/
Univ. Grenoble Alpes, CNRS                                                    Tél: +33 (0)4 76 74 86 68                
414 Rue de la Piscine
38400 Saint Martin d’Hères  
France
Email: ***@***.***
___________________________________________________________________________
