### ISSUE TITLE
Automatically compute the field of view and the sampling

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#25]
When creating image (see #15 ) FoV and sampling estimates should be automatically set
- the fov is &lambda; / D with D the size of telescope
- the pxiel size (sampling) is &lambda; / (2 B) with B the largest baseline

**Comment by jsy1001** [comment]
BSMEM works best with pixel size λ / (6 B).

**Comment by buthanoid** [comment]
Related to https://github.com/JMMC-OpenDev/oimaging/pull/108
