### ISSUE TITLE
hide  FLUX & FLUXERR in GUI

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#26]
FLUX & FLUXERR are a bit useless for the current algorithm. I suggest to hide those keywords and to set default values to FLUX=1 FLUXERR=0.01

**Comment by FerreolS** [comment]
As  setting FLUXERR arbitrarily  sometimes drastically changes the behavior of the algorithm we should let the user tune it, but  still hidding FLUX=1 for the moment.

**Comment by buthanoid** [comment]
Done it
But as we discussed in the previous issue https://github.com/JMMC-OpenDev/oimaging/issues/58,
WISARD has been set to 1E-6 on its side, so I would say let's revert the commit on WISARD's side too before pushing.

**Comment by GillesDuvert** [comment]
Ready to remove the commit on WISARD that was setting FLUXERR to 1E-6?
Then FLUXERR MUST be set to 1e-4 in the GUI, not 0.01

**Comment by buthanoid** [comment]
Created Pull Request https://github.com/JMMC-OpenDev/oimaging/pull/93 to do it.
- wisard default flux err set to 10e-4
- service default values applied at OImaging reset (startup), it was not the case

**Comment by bourgesl** [comment]
PR merged
