### ISSUE TITLE
hide THRESHOLD keyword in WISARD

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#29]
This convergence WISARD keyword is not usefull for the end user and we should hide it.

**Comment by buthanoid** [comment]
User manual says :
"By default set to the machine precision in simple precision (approximately
1.19 ×10−07), although computations are performed in double precision."
For tests and a quick-look of the results, set THRESHOLD to ∼10−6."
The current OImaging sets the default to 10-6.
But if I read correctly the doc I should let WISARD choose this parameter (and so remove the default 10-6 value in OImaging)
