### ISSUE TITLE
LoadOiFitsFile clears image HDUs, and does not sync keywords INIT_IMG and RGL_PRIO with Run Form widgets

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#36]
See https://github.com/JMMC-OpenDev/oimaging/pull/34#issuecomment-947740783
Also https://github.com/JMMC-OpenDev/oimaging/pull/34#issuecomment-947760510
and the comments that follow

**Comment by buthanoid** [comment]
Erroneous clearing of image HDUs have been fixed in https://github.com/JMMC-OpenDev/oimaging/pull/35 ; see IRModel.java line 281 
`// avoid modifying input file while loading OIFits (reentrance)`

**Comment by bourgesl** [comment]
Please restore selected images from INIT_IMG & RGL_PRIOR keywords ? 
see TODO: https://github.com/JMMC-OpenDev/oimaging/blob/11df263c3eb432ee156ad059d7e9cca113aea780/src/main/java/fr/jmmc/oimaging/model/IRModel.java#L197

You need a lookup method: getFitsImageHDU(hdu name) using the hdu name present in the file and traversing the FitsImageHDU images of the input file (not the image library)

**Comment by buthanoid** [comment]
I encountered that the input form is using the image library for the combo box.
Since the combobox need to be synced with the Oifitsfile associated to the input form, it means that I can only select a HDU which is in the library.
Thus, after I do the lookup in the input file as you explained, 
I need to select an equivalent HDU  in the image library.
Equivalent means same address, or same checksum.
Do you agree ?

This is for Loading OIFItsFile scenario. 
Then, the murphy's law tells that this will not work in the "Run" scenario, where we refuse to add an INIT_IMG hdu to the library because we know it is a duplicate. Indeed we cannot find an equivalent one in the library by using checksum, as you explained in https://github.com/JMMC-OpenDev/oimaging/pull/39#issuecomment-964930379

I am going to think about this

**Comment by buthanoid** [comment]
fixed by https://github.com/JMMC-OpenDev/oimaging/pull/39/commits/3c561cbbe504fe6dce50a8992909bab88e5b3d13

**Comment by bourgesl** [comment]
Fixed by PR#3¥
