### ISSUE TITLE
Display Keywords not updated when modifying viewport

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#40]
When you modify viewport, the keywords `NAXIS*` in "display keyword" still display obsolete values. They do not account for the new image size.

Scenario:
- Load an image 32x32 
- Click on the button "display keywords" in viewerpanel and check that the keywords `NAXIS1` and `NAXIS2` are equal to 32.
- Click on "viewport" button, set "FOV" to 64, click on "update", then click on "OK"
- Observe that the image is now 64x64
- Click on the button "display keywords" in viewerpanel and check that the keywords `NAXIS1` and `NAXIS2` are still equal to 32.
- Bug: `NAXIS1` and `NAXIS2` should be equal to 64.

Note that if you register the file, the keywords are correct in the file.

**Comment by bourgesl** [comment]
That's true: displayed keywords come from the `FitsHDU.headerCards` (only read from file) whereas the modified image (`FitsImage` / `FitsImageHDU`) is correct: `FitsImage` fields are up-to-date and used when saving the image as a FITS image file.

Solution: once the image edition is done in `ViewerPanel.processFitsImage()`, updating `FitsHDU.headerCards` is necessary to update the displayed keywords: see FitsImageLoader and FitsImageWriter processImageKeywords() that convert `FitsImage` fields <=> FITS header

**Comment by buthanoid** [comment]
Note that `NAXIS1` is not the only keyword concerned, `CDELT1` is also concerned and maybe others too.

Proposal 1: call `FitsImageWriter.processImageKeywords` at the end of `ViewerPanel.processFitsImage` 
==============================================================================
Create an empty `Header`, fill it with `FitsImageWriter.processImageKeywords`, then iterate through the headerCards in the Header to update the headerCards in the `FitsImageHDU`.

Proposal 2: modify the setters in `FitsImage` so they also update headerCards in `FitsImageHDU`
========================================================================
A setter as `setSignedIncCol` will also update the value in the headerCard of the `FitsImageHDU` parent.

**Comment by bourgesl** [comment]
I hate code duplication so solution 2 is discarded as all setters should update their corresponding header card.

Maybe there is a possible short-cut path to avoid calling FitsImageWriter + Loader (keywords) to reconstruct a list of header cards...

**Comment by buthanoid** [comment]
All I saw for now is functions that use the Header interface, so it implies going from the FitsImage fields to the Header, then from the Header to the FitsImageHDU keywords.
I will search in other classes if there is something doing this without the Header step

**Comment by bourgesl** [comment]
Certainly it is safer to use FitsImage to nom.tam.fits.Header to FitsImageHDU.headerCards for now.
Please avoid creating a full nom.tam.fits.ImageHDU with copied data if possible.

**Comment by buthanoid** [comment]
https://github.com/JMMC-OpenDev/oimaging/pull/51
I think that `createHDUnit` does not copy the data. 
However `processKeywords` is not so satisfying because it duplicates some headerCards, i.e it does not update `NAXIS1` but add a second `NAXIS1` at the end.

**Comment by bourgesl** [comment]
Yes createHDUnit() is low-overhead, so good.
It looks buggy that the NAXIS1and NAXIS2 keywords are either duplicated or incorrectly set from FitsImage !

**Comment by buthanoid** [comment]
I can resolve it by adding the following middle line:
```java
final BasicHDU basicHdu = FitsImageWriter.createHDUnit(copyFitsImageHDU);
 copyFitsImageHDU.getHeaderCards().clear();
FitsImageLoader.processKeywords(new OIFitsChecker(), basicHdu.getHeader(), copyFitsImageHDU);
```
It clears the header cards of `copyFitsImageHDU`. Normally, all of them have been kept in `basicHDU`, and correctly updated, so we don't lose header cards. 

The problem was in `FitsImageLoader.loadHeaderCards`, a function which seems to be meant to initiate header cards, so it does not check if there is already an existing header card, it just add it to the list. This explains the duplicates.

**Comment by bourgesl** [comment]
LGTM, please set checker to null and we're good.
