### ISSUE TITLE
Selected initial image set to null whereas list of inital images contains no null element (also, list of init images is sometimes empty)

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#41]
The field selectedInputImageHDU is set to null in several places and times.
It is supposed to be synced with the selected item in the list of initial images (gui combobox).
The problem is that this list has no null element. Moreover, sometimes it has no elements at all, which is also a problem.

I suggest to always have a null element in the list. There is already a simi-null singleton for this : NULL_IMAGE_HDU which is used for RGL_PRIO.

This way, when selectedInputImageHDU is set to null, the syncUI will correctly select NULL_IMAGE_HDU in the list. Moreover, the list will never be empty, which is better.

By doing this we must look at how RGL_PRIO was handling cases: some algorithms does not support that INIT_IMG keyword is missing, and the NULL_IMAGE_HDU will produce an empty value for INIT_IMG, so it is equivalent to INIT_IMG keyword missing. Said differently, some algorithms must not be runned if INIT_IMG is set to NULL_IMAGE_HDU.

By doing this, we could at the same time, or in a later time, simplify some code by enforcing that selectedInputImageHDU is never the exact Java null value. So instead of handling both null and NULL_IMAGE_HDU cases, we will just handle the latter one.

**Comment by bourgesl** [comment]
I am lost in translation.

I propose to have:
- IRModel selectedInputImageHDU and selectedRglPrioImageHdu are null or a reference to the image library (NULL_IMAGE_HDU is never present here)
- SoftwareSettingsPanel handles the GUI (combo box). if needed utility methods can here make conversions (null <=> NULL_HDU) if it is simpler.

Could you describe a concrete case ?

**Comment by buthanoid** [comment]
I fail to remember the scenario that happened thursday evening. I suppose that settles this issue. Next time I will write immediately to not forget

**Comment by buthanoid** [comment]
I "encountered" the issue again. Not in the current build but by removing one specific line of code. 

#### Description of the problem

When there is no HDU in the library, there is no item in the list of input images, and the selected Input Image HDU is null. If you add one HDU (named "AAA") in the library, but forget to select a HDU as input image, you get into an inconsistent state: the list of input images has selected its only item "AAA", but you still have no selected input image HDU (consequently, the HDU is not present in the OIFitsFile, and the parameter INIT_IMG is empty).

#### Scenario

I don't think that it can happen in the current build because we always selected an input image. It happened to me when I removed the setSelectedInputImageHDU(firstImageEquiv); call from IRModel.addFitsImageFile(). So remove the line, then:
- Select software BSMEM
- Load an image
- Observe that the list of input images has selected the first image of your file
- Observe that the INIT_IMG param is still empty
- In the debug mode you can observe that selectedInputImageHDU is still null
- Bug: inconsistent state, since the list has selected one HDU, the INIT_IMG param should name that HDU, and the HDU should be refered by the selectedInputImageHDU field, and the HDU should be in the OIFitsFile.

#### Resolve proposal

Since it is not a bug in the current build I don't know if you consider it as an actual bug. If I was to correct it I would add the NULL hdu all the time in the list of input images, so you always have something selected, thus when you add some images in the library it does not change your selection.

**Comment by buthanoid** [comment]
#### Erratum: there is indeed a bugging scenario in the current build
- Select BSMEM software (because it does not support missing input image)
- Add an image "AAA" to the library and select it as input image
- Load a OIfitsFile that contains targets but *no image*
- So the loading set selected input image hdu to null
- But since the loaded input form contained no init image, the loading keeps selected input image hdu to null
- But the input image list has only one element : the image "AAA". it is unable to reflect the "null selected input image hdu".
- So we are in a inconsistent state

**Comment by buthanoid** [comment]
The bug is still here

**Comment by bourgesl** [comment]
Please give technical details

**Comment by buthanoid** [comment]
#### Description

BSMEM software does not allow missing input image. Thus, there is no item `[No Image]` in the list of input images.
When you load an Oifits file that has no `INIT_IMG` set, it must be reflected in the input form.
The problem is that the input form is unable to do so: indeed the list of input images has no `null` value, nor `null` equivalent value.

If you don't believe it is an inconsistent state, after the scenario, observe that the input params has `INIT_IMG` set to null value. But click on something on the input form (for example, increase maximum iterations). Observe that the oifitsfile will be synced with the input form, i.e the `INIT_IMG` will be set to `AAA`. 
When we increase maximum iterations, if that also modify the param `INIT_IMG`, then we were clearly in an inconsistent state.

#### Scenario 

See scenario from comment https://github.com/JMMC-OpenDev/oimaging/issues/41#issuecomment-981723031

#### Observations

It does not happen for WISARD software for example. Since WISARD allows missing input image, the list of input images always contains the item `[No Image]`. When loading an OIfits file with no `INIT_IMG` set, the `[No Image]` item is used to reflect the null value.

#### Proposal

AMHO the list of input images should always have a `[No Image]` item, in order to reflect loaded OIFits file with missing `INIT_IMG`. That implies to check that the action `Run` is disabled when `[No Image]` is selected and the current software disallow missing initial image.
