### ISSUE TITLE
WISARD regul & parameters

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#42]
After a discussion with @GillesDuvert last month we decided that:
- rename `SCALE` as `RGL_WGT`
- keep only L1L2White and soft support. 
- soft support need an image indicated by `RGL_PRIO' 
- L1L2White have only a single specific parameter (in addition to `RGL_WGT`) : `DELTA`

**Comment by GillesDuvert** [comment]
All done I believe.

**Comment by FerreolS** [comment]
> All done I believe.

Good!

Let just propage the changes in the GUI (that is masking extra-parameters)

**Comment by buthanoid** [comment]
I will:
- remove L1L2, PSD, and TOTVAR, from the RGL_NAME selection list.
- remove DELTA specific parameter when L1L2WHITE is selected
- keep the RGL_PRIO available no matter the RGL_NAME selected (because the current code works that way and changing this behaviour would take more time that the benefits AMHO)

**Comment by buthanoid** [comment]
There was this TODO in the source code, just above the WISARD parameters for RGL_NAME:
```
    // TODO:
    // - L1L2WHITE: add MEAN_OBJECT KW: An image, rescaled NP_MINxNP_MIN as INIT_IMG. (NULL)
    // - SOFT_SUPPORT: add MU_SUPPORT (0.5)
    // either:
    //     - MEAN_OBJECT : An image, rescaled NP_MINxNP_MIN as INIT_IMG. (NULL)
    //     - FWHM : Full Width Half maximum of a lorentzian used as prior, in pixels (3.) (less prefered as costly)

```
This TODO comment may be obsolete. Should I keep it ?

Also, I removed completely the DELTA parameter since it was not used anymore.

**Comment by buthanoid** [comment]
Ferréol is going to check that modifications are correct.

This pull request is meant to be synchronized with the server update.

**Comment by FerreolS** [comment]
fix typo in the fix comment :
L1L2White have only a single specific parameter (in addition to RGL_WGT) : DELTA

**Comment by buthanoid** [comment]
Merged too soon. fix scale -> delta in https://github.com/JMMC-OpenDev/oimaging/pull/53.

**Comment by buthanoid** [comment]
Note that to hide RGL_PRIO only when service is WISARD and RGL_NAME is L1L2WHITE, the hack starts to be a bit dirty (contrary to the hack used to hide FLUXERR).
To do it cleanly it would need to rework the way standard keywords are enabled/disabled. This is a longer job. Does it worth it ? Note that the RGL_PRIO will be kept in the OiFitsFile even if it is hidden in the GUI.

**Comment by bourgesl** [comment]
I totally disagree as it should be already supported.

**Comment by bourgesl** [comment]
I mean:
- use validate to modify flag rglPriorNeeded according to RGL_NAME:
- fix  supportsStandardKeyword() to use a boolean flag rglPriorNeeded in:
 ​    ​public​ ​boolean​ ​supportsStandardKeyword​(​final​ ​String​ ​keywordName​)...

That should hide the RGL_PRIOR field when supportsStandardKeyword(RGL_PRIOR) == false.

**Comment by buthanoid** [comment]
In https://github.com/JMMC-OpenDev/oimaging/pull/56, at the same time of some update on Mira params default values

Note: I used `update()` instead of `validate()` because the latter did not change the values on good time.

**Comment by GillesDuvert** [comment]
Coming back to the subject of this issue (top), I think it should be reviewed as now I'm not sure everything is OK with Wisard+rgl_prior
