### ISSUE TITLE
BSMEM parameters

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#43]
@jsy1001 what are the purpose of parameters `RGL_ALPH`and `RGL_BETA` that appear in OImaging when using BSMEM? I can't find a documentation for that. Does `RGL_ALPH` is equivalent to the regularization parameter `RGL_WGT`?

**Comment by jsy1001** [comment]
I've checked the source code, and neither of those two parameters are used by BSMEM. I'm not sure why they appear in OImaging.

**Comment by FerreolS** [comment]
Thanks. So let's remove them.

**Comment by buthanoid** [comment]
https://github.com/JMMC-OpenDev/oimaging/pull/46
