### ISSUE TITLE
FLUXERR is not available for WISARD

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/oimaging#58]
FLUXERR seems to be set to 0.01 by the GUI but there is no way to change this value. No surprise WISARD does not converge.

I can just remove FLUXERR from the list of user-settable values and put it to something like 1e-6, a reasonable default, but in this case, any mention of FLUXERR in the input or output tables should be supressed, and those tables are in charge of oimaging.

**Comment by FerreolS** [comment]
My fault, I have suggested to remove FLUX and FLUXERR from the GUI to not confuse the user as it is difficult to have rational to set it. Every algorithm as his own behavior regarding this (MiRA prefers FLUX=1 and FLUXERR=0). I suggest to keep this keyword set to some default by the GUI. We will probably put these keyword in a more expert mode of the GUI or when we will cope with polychromatic algorithms.

**Comment by GillesDuvert** [comment]
OK, that is just what I did in my last commit :smile:

**Comment by FerreolS** [comment]
Sorry Gilles, what I said was not clear enough. `FLUX` and flux `FLUXERR` are keywords from OI-Interface standard so WISARD should use it. 
What I suggest was to set it at a given value (you may tell us what is the best value) in the GUI and not in WISARD.  We may make this keyword accessible again in the future.

**Comment by GillesDuvert** [comment]
Let's put it to 1E-6

**Comment by buthanoid** [comment]
Linked to https://github.com/JMMC-OpenDev/oimaging/pull/62

**Comment by bourgesl** [comment]
I will fix your 2 PRs asap

**Comment by bourgesl** [comment]
Fixed in integrated #62
