### ISSUE TITLE
logs to stderr print with %ERROR%

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/oimaging#59]
IDL (and GDL must mimic that) prints all internal messages to stderr.
This is necessary to enable further filtering between IDL-generated messages and user-created ones, such as with the 'PRINT' command.
In a course of an IDL program, unless a filter is set up, these informational messages are seen by the user and they seem to like it since they were not removed in 40 years of IDL.
But in OImaging, they come with %ERROR% added, which is ugly and wrong.
If I filter these messages out, we gain in clarity but **will never know why a reconstruction fail.**
The simplest is to completely avoid messing with programs outputs and remove this feature.

**Comment by buthanoid** [comment]
From team debrief: it only occurs in local mode.

**Comment by bourgesl** [comment]
I fixed gdl calls:
gdl ... 2>&1
