### ISSUE TITLE
Mira RGL_NAME value in the table of results disappear

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#60]
**Reported by Ferréol.**

#### Problem
The value for the column 'RGL_NAME' disappear in the table of results. It is for MIRA runs.The parameters table still contain the value, only the result table do not display it. It happens when you make another run. 

#### Scenario
- Select a target and an initial image and run Mira
- Observe that the RGL_NAME in result table and in parameters table contains a value
- Run Wisard
- Observe that the RGL_NAME in result table for Mira run has disappeared. bug !

**Comment by buthanoid** [comment]
I think I spot the problem.
The column are not duplicated. Hence if you have column RGL_NAME both in INPUT and OUTPUT params, the OUTPUT will be chosen.
Then, consider that MIRA have only INPUT RGL_NAME and neither OUTPUT RGL_NAME, 
and that WISARD have both INPUT and OUTPUT RGL_NAME.
Thus, the table will chose the output columns, and MIRA has none.

**Comment by FerreolS** [comment]
I think we should stick with what is written in the OI-Interface document:
so RGL_NAME should be in INPUT and ignored in output.

**Comment by buthanoid** [comment]
I am not trying to have the last word, but I did not found mention of it in https://raw.githubusercontent.com/emmt/OI-Imaging-JRA/master/doc/interface/OI-Interface.pdf

Also I was referring to the following sentence page 7:
"The output file shall contain a copy of the input parameters".

What do you think ?

If this is true, we could also provide a patch that copy the input parameters that are not present in output parameters.

**Comment by bourgesl** [comment]
I agree such specific column could use a specific resolver to try getting information from  (OUTPUT, INPUT or HARDCODED) (priority).

**Comment by buthanoid** [comment]
done in https://github.com/JMMC-OpenDev/oimaging/pull/67
