### ISSUE TITLE
Modify Image transforms the wrong image if the target changes during dialog

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#65]
### Summary 
If you call Modify Image, but the displayed image in the ViewerPanel is changed when you are interacting with the dialog (it typically happens when a run finishes), when you confirm the dialog the wrong image is modified. 
What is especially bad in the case of a run finish is that the run's result image gets modified. 

### Scenario
- Launch empty OImaging 
- Load a target
- Create a gaussian
- Run Wisard 
- Wait for Wisard to end
- Run Wisard again (normally the last result image has been automatically set as init image)
- Before Wisard ends, click on the result in the table of results
- Before Wisard ends, you have the result image of the first run displayed. 
- Before Wisard ends, click on Modify Image. A copy of the HDU has already been made (you cannot see it in the library yet).
- Wait for Wisard to end, with the modify dialog still opened.
- After Wisard ends, modify FOV (200 for example, to make a visible difference) and confirm the dialog
- Problem ! Observe that the copied HDU prefixed by "modified" is in the image library but have not been modified at all
- Problem ! Observe that the result image of the last result is the one that has been modified !

### Analysis & proposals

AMHO the problem resides in the design. The transforming function is using the currently displayed image. It would be way better that the transforming function just receives the image as a parameter. It would then be lot less dependent on the context. This way, we don't have to be careful to maintain the image during the Modify Image dialog, as we chosed the image at the beginning of the process, and we point at it directly, not by the intermediary of some display context.

If you disagree, I suggest another proposal (which actually is not entirely incompatible with the previous one).
We could have a display panel just for currently modified image. So when you click on modified image, you actually reference and plot the copy of the original targeted image, in that new modification panel. So the original panel can be updated by whatever event, it does not impact the modification panel. 
The benefit is that we can keep the current design of the transforming functions. Also we could, with not so much work, add a "live display" of the modification before confirming it, which would be a nice functionality. We could also permit the user to choose a HDU name different that the copy of the original one prefixed with "modified".

What do you think ?

**Comment by bourgesl** [comment]
Nice concurency issue ... fix in progress !

**Comment by bourgesl** [comment]
Fixed in PR #62

**Comment by bourgesl** [comment]
Fixed in oiexplorer-core and integrated #62
