### ISSUE TITLE
Default Keywords list

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#68]
We should provide a default keywords list and a mean to reset to these default value

**Comment by FerreolS** [comment]
IMHO, these default should be (in this order?):
- INDEX
- TARGET
- SOFTWARE
- INIT_IMG
- RGL_NAME
- RGL_WGT
- NITER
- CHIQ
- SUCCESS
- RATING
- USERNOTE
- FOV 
- FILE

**Comment by buthanoid** [comment]
OImaging PR https://github.com/JMMC-OpenDev/oimaging/pull/70
JMC PR https://github.com/JMMC-OpenDev/jmcs/pull/1
I confess that the code is not so pretty, but it had to fit in the current one, which lacks flexibility. If you think of a better way, please tell me :+1:

**Comment by bourgesl** [comment]
Lost in translation...
The design is important: jmcs is generic java widgets + features; each application have to deal with its own preferences, that's the classical approach in Object Oriented design: separation of concerns/aspects.

**Comment by buthanoid** [comment]
Updated: 
PR OImaging https://github.com/JMMC-OpenDev/oimaging/pull/70
PR JMCS https://github.com/JMMC-OpenDev/jmcs/pull/1
PR ASPRO2 https://github.com/JMMC-OpenDev/aspro/pull/3

According to your advice the code has been kept in JMCS but completed to be able to answer to any need from the applications. 
The "complicated" part of the logic resides in the OImaging PR where the default list are used not only to reset to the initial list (just before the editor starts) but also to purge any column that is not part of the results, not hardcoded, and not default.
The Aspro PR consists in giving default lists that are exactly the ones just before the editor starts, and to adapt the existing code to the new result value of the show editor (it puts its return value in the parameters now).
