### ISSUE TITLE
Missing keyword in MiRA

### ISSUE THREAD

**Issue by FerreolS** [JMMC-OpenDev/oimaging#74]
MiRA does not return (or remove?) the following keywords in INPUT_PARAM table:
- TARGET
- INIT_IMG

**Comment by buthanoid** [comment]
Just tested directly on ymira and it works. However the initial image hdu is lost between this and OImaging. I am going to look if the GDL script keeps the initial image

**Comment by bourgesl** [comment]
Oimaging UWS server has a mira-ci.sh script to give the options:
`ymira -oi-imaging -save_visibilities ...`

**Comment by buthanoid** [comment]
Yes it fills the keyword but the HDU is still missing.

Does this line in GDL prevent the writing of _others_ hdus (including the initial image hdu) ?

https://github.com/JMMC-OpenDev/wisard-ci/blob/main/model2oifits.pro line 347
```gdl
; do not write unknown arrays.
;  for i=0,n_elements(oiotherarr)-1 do mwrfits,*(oiotherarr[i]),output,*(oiotherheadarr[i]),/silent,/no_copy,/no_comment
```

this `oiotherarr` seems to be filled at line 264:

```gdl
endif else begin           ; every other tables: may contain an hduname image
        oiother = ptr_new( mrdfits(input,i,header) )
        ; eventually, if has an HDUNAME, get it
        hduname=strtrim(sxpar(header,"HDUNAME"),2)
        if hduname ne '0' then hdunames[i]=hduname
        oiotherhead = ptr_new( header )
        oiotherarr = (n_elements(oiotherarr) gt 0)?[oiotherarr,oiother]:oiother
```

**Comment by bourgesl** [comment]
No this code reads other binary tables ...
I quickly looked at the gdl script and it load the primary image (input image) in hd0:
```
;read first header
  hdu0=mrdfits(input,0,main_header)
```
It seems easy to write it too (but maybe some keywords must be fixed):
`mwrfits,hdu0,output,main_header,/create,/silent,/no_copy,/no_comment`

Any idea @GillesDuvert ?

**Comment by GillesDuvert** [comment]
the oiotherarr structure contains 'other' binary tables, that are indeed not written, but this can be uncommented. As our new policy is to write back everything, I suggest to uncomment it. The requested image must be there.

**Comment by buthanoid** [comment]
I found a way to write the initial image in the same way that the result image is written. I think it is consistent with the actual MiRA output and the rest of the .pro script.
I will also uncomment the "other" binary tables and make some tests to see what is inside these other tables

**Comment by bourgesl** [comment]
Integrated in coming oimaging server
