### ISSUE TITLE
Radio button RGL_PRIO selected but ViewerPanel shows INIT_IMG

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#79]
### Description

In the input form GUI, when the RGL_PRIO radio button is selected, but there is no image chosen for RGL_PRIO, the ViewerPanel will display the INIT_IMG.
Problem: it is confusing for the user to have manually asked for RGL_PRIO, and still getting the INIT_IMG shown. The user can erroneously conclude that the RGL_PRIO image is the one that he sees.

### Scenario

- Open a clean OImaging
- Select BSMEM software
- Create an image. It should be chosen as INIT_IMG. Normally, the RGL_PRIO image is set as "[No Image]".
- Select radio button RGL_PRIO (normally, the INIT_IMG radio button was selected as default).
- Problem: look at the viewerPanel and observe that it stills display the INIT_IMG image whereas you asked for the RGL_PRIO image !

### Technical observations

The viewerPanel seems to display the images contained in the OIFitsFile, so when there is only an INIT_IMG image, it seems unable to do something else than displaying it. It has no "empty RGL_PRIO item" to select and display.

**Comment by buthanoid** [comment]
### Proposal

I propose to make the following updates:

- remove the radio buttons because there is already a image selection list in ViewerPanel
- keep the field storing which image is displayed in IRModel, but fix it because when the ViewerPanel list changes, it does not make the model change. use a updateModel design. introduce constants for the field. the updateModel in IRmodel will cleverly set the input: if there is no INIT_IMG, it will not keep the selection on INIT_IMG, and same for RGL_PRIO. 
- `Create Image` will ask whether to select the created image as INIT or RGL (or both), with default to INIT only
- the image selection list of ViewerPanel will plainly display roles in the label (INIT and RGL), so it is clear to the user which image he is selecting or viewing

This resolves the present issue, because the user can no longer select "RGL_PRIO" on the radio button, so there is no more incoherence with the viewer panel list.

**Comment by buthanoid** [comment]
Related to this issue:
- the RGL_PRIO keyword is always here with a value even when there should be no RGL_PRIO 
- the INIT_IMG radio button should be disabled when there is no init image to display

**Comment by bourgesl** [comment]
For exeter, only quick bug fixes will be possible:
- leave the ViewerPanel display what it wants (input file browser)
- remove RGL_PRIO keyword / image HDU if not needed
- the image selection on the input panel should be fixed to properly show INIT_IMG and RGL_PRIOR if supported and the selected item must be updated too (no RGL_PRIO => INIT_IMG selected). If only 1 choice, radio buttons are disabled and the INIT_IMG should be displayed. 
- If INIT_IMG = [No Image], what should contain the input file and what should display the ViewerPanel ?

**Comment by buthanoid** [comment]
started in https://github.com/JMMC-OpenDev/oimaging/pull/106 where I began by nullifying RGL_PRIO when it is unsupported.

**Comment by buthanoid** [comment]
I think I am done, what do you think ? It is a bit "strict" with the disabling of the radio buttons but it is more consistent. 
I don't plan to add the synchronization from ViewerPanel to IRModel. I don't see how I would fit it nicely in the code so I would stop here.

**Comment by bourgesl** [comment]
Looks good and working well !
