### ISSUE TITLE
Alternative checksum for FitsImageHDU: data + some keywords

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#82]
The imageLibrary refuse duplicate FitsImageHDU, using their checksum to compare them.

Problem is that the checksum function is absolute : it will use every information, for example the hduName. So two FitsImageHDU will be considered different when only their hduNames differ.
In consequence, the library contains some FitsImageHDU that we, the users, will consider as duplicates, because they behave as duplicates for every use we have of them. These FitsImageHDU should clearly be refused in the library.

To achieve that, we need an alternative checksum function that is less strict than the existing one.
It should focus on the information that is important in the eyes of the user (and of the algorithm softwares).

As a first proposal, the alternative checksum will use the data (i.e the images) and a list of keywords which remains to be defined.

**Comment by buthanoid** [comment]
Technical idea:

See function `FitsImageHDU.updateChecksum`.
It calls `BasicHDU imgHdu = FitsImageWriter.createHDUnit(this)` to then compute the checksum on this object.
Instead of this, we could give it a copy of the current `FitsImageHDU`, where the header contains only our list of selected keywords. That would be an easy way of computing the alternative checksum without touching many things.

I think the imageLibrary could be a Map with the alternative checksums as keys ?

**Comment by bourgesl** [comment]
I would clarify that checksum were used as an easy but brute-force solution to determine if 2 image HDUs are the same.

Here an alternative `Matcher` or comparison of 2 HDUs is needed to determine if 2 images are equivalent in the image library (hdu name is ignored, coordinates can be rounded or expressed in different units ...)

We shortly discussed an alternative solution: 
- check image dimensions (rows/cols) then compute a checksum on image values (flux) = datasum(float[] data) for every FitsImage
- use image area (image area coordinates in radians) and the image wavelength
This works for 1 FitsImage but how to generalize to the FitsImageHDU ? 
both HDUs could be compared using their fitsImages list and compared 1 by 1. 

To be described in more details before implementation

**Comment by buthanoid** [comment]
I wrote a first version that I unfortunately forgot to push from my home computer :robot: . I will make a review here the best I can.

Recall that the goal is to **write an equivalence function** for `FitsImageHDU`, which consists of a Header(H) and an Image Data(D). The image data can contains several images. 

The equivalence function proceeds by verifying iteratively the following steps. Each step compare one field of the two `FitsImageHDU`. As soon as a step fail, the function return "false'" for "these two `FitsImageHDU` are considered non-equivalents".

1. nb of images (int) must be equal
2. for each image:
3. length of the two dimension pixel data array (nb of columns (int) and nb of rows (int)) must be equal
4. absolute sky increment by row and by column (two double radian/pixel) must have difference <= **1e-10**
  The absolute property makes that mirror images are considered equivalent.
5. position in the sky (two double radian) must have difference <= 1e-10
6. coordinates of the reference point in the data array (two double) must be equal
7. rotation angle (double degree) must have difference <= 1e-10
8. wavelength values: reference point (double), value at the reference point (double meter), increment (double meter/pixel) must have difference <= 1e-10
9. for each pixel (for each column and for each row):
10. each pixel (float) must have difference <= **1e-((number of cols) * (number of rows) * 1000)**

Consider that there is two kinds of values:
- values with a "**known range**": the position in the sky in radians, we know the size of the error we need (I picked 1e-10, is that correct ?)
- values with a "**dynamic range**": the pixel array is normalized so the sum of pixels is equal to 1.0. Thus as the array gets bigger, the values tend to be smaller. I used the average value by pixel, divided by 1000. What do you think ? In fact, I am not expert of the float format, but I think the most adequate way would be to compare two pixels with an **error computed from their magnitude**, instead of a unique magnitude defined for all pixels. If you feel a more clever epsilon should be used (than the current one), let me know.

About floating points errors: note that a asked for an equality for the reference point coordinate because i think it is not subject to computation. But it could be possible than after the round-trip with the softwares, even **an untouched decimal will change** a bit. I need to check this yet.
