### ISSUE TITLE
Sanitize file names 

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oimaging#97]
### Problem
If you load a file with a *considered bad practice* name, i.e a space within, it will produce a erroneous command call for BSMEM local (maybe for other softwares too)

### Scenario

- Load a file with bad practice name, my own example was "PIONI.2021-02-08T07 25 28.085_oidataCalibrated.fits" 
- Launch BSMEM local
- It fails with the error : 
```
cmd: "bsmem-ci /tmp/PIONI.2021-02-08T07 /tmp/25 /tmp/28.085_oidataCalibrated.fits7310994219721603764.export-6.fits /tmp/PIONI.2021-02-08T07 /tmp/25 /tmp/28.085_oidataCalibrated.fits7310994219721603764.export-6.fits.output.fits"
```

### Solution Proposal

Sanitize file names: remove any character that could be interpreted by the shell, etc

**Comment by gmella** [comment]
Yes we agree. Next method  should help to fix this issue:
fr.jmmc.jmcs.util.StringUtils.replaceNonAlphaNumericCharsByUnderscore(anyFilename)

**Comment by buthanoid** [comment]
See https://github.com/JMMC-OpenDev/oimaging/issues/111#issuecomment-1161976570

**Comment by bourgesl** [comment]
Duplicate #120
